name: japcipher
category: "crypto"
title:     "Японский шифр"
points:   150
author:   ksixty
description: |
  <p>Наш воображаемый друг из Японии снова на связи! На этот раз у него для вас совсем другая загадка. Ему слово...</p>
  <p><b>Добавлено в 13:30:</b> в тексте утверждается, что сообщение зашифровано довольно простым и известным афинным шифром. Обратите внимание на то, как выглядит маскот страницы.</p>
generator: run_generator.sh
daemon: app/run_daemon.sh
daemon_isolate: false
daemon_socket: "japcipher.sock"
